import streamlit as st
from src.report_generator import generate_markdown_report
from src.constants import (
    ATS_SCORE,
    DEFAULT_RECOMMENDATION_ICON,
    MARKDOWN_REPORT_BUTTON_LABEL,
    MARKDOWN_REPORT_FILE_NAME,
    MARKDOWN_REPORT_MIME_TYPE,
    MATCHING_SKILLS,
    MISSING_SKILLS,
    RECOMMENDATION_LEVEL,
    RECOMMENDATION_LEVEL_ICONS,
    RECOMMENDATIONS,
    STRENGTHS,
    SUMMARY,
    EXCELLENT_MATCH,
    EXCELLENT_MATCH_DESCRIPTION,
    EXCELLENT_MATCH_ICON,
    GOOD_MATCH,
    GOOD_MATCH_DESCRIPTION,
    GOOD_MATCH_ICON,
    NEEDS_IMPROVEMENT,
    NEEDS_IMPROVEMENT_DESCRIPTION,
    NEEDS_IMPROVEMENT_ICON,
)
from src.ui_messages import(
    NO_MATCHING_SKILLS_MESSAGE,
    NO_MISSING_SKILLS_MESSAGE,
    NO_RECOMMENDATIONS_MESSAGE,
    NO_STRENGTHS_MESSAGE
)


def _display_tag_list(title: str, icon: str, items: list, empty_message: str):
    """
    Display a titled list of tags.
    Parameters:
        title (str): Section heading.
        icon (str): Emoji displayed before the heading.
        items (list): Items to display as tags.
        empty_message (str): Message displayed when the list is empty.
    Returns: None
    """
    st.subheader(
        f"{icon} {title}"
    )
    if not items:
        st.caption(empty_message)
        return

    tag_text = "   ".join(
        [
            f"`{item}`"
            for item in items
        ]
    )
    st.markdown(tag_text)


def _display_score_section(ats_score: int):
    """
    Display the ATS score section.
    Parameters: ats_score (int): ATS score generated by Gemini.
    Returns: None
    """
    score_status, score_icon, score_description = (
        _get_score_status(
            ats_score=ats_score
        )
    )
    st.subheader(
        "🎯 ATS Match Score"
    )
    st.metric(
        label=f"{score_icon} {score_status}",
        value=f"{ats_score}%"
    )
    st.progress(
        ats_score / 100
    )
    st.caption(score_description)


def _display_recommendation_level(recommendation_level: str):
    """
    Display the AI recommendation level.
    Parameters: recommendation_level (str): Recommendation level returned by Gemini.
    Returns: None
    """
    icon = RECOMMENDATION_LEVEL_ICONS.get(
        recommendation_level,
        DEFAULT_RECOMMENDATION_ICON
    )
    st.subheader(
        f"{icon} {recommendation_level}"
    )


def _display_summary(summary: str, recommendation_level: str):
    """
    Display the AI-generated summary and recommendation level.
    Parameters:
        summary (str): Overall assessment generated by Gemini.
        recommendation_level (str): Recommendation level generated by Gemini.
    Returns: None
    """
    st.subheader(
        "📋 Overall Assessment"
    )
    st.info(summary)
    _display_recommendation_level(
        recommendation_level=recommendation_level
    )


def _display_recommendations(recommendations: list):
    """
    Display resume recommendations.
    Parameters: recommendations (list): Improvement recommendations.
    Returns: None
    """
    st.subheader(
        "💡 Recommendations"
    )
    if not recommendations:
        st.caption(
            NO_RECOMMENDATIONS_MESSAGE
        )
        return
    for recommendation in recommendations:
        st.markdown(
            f"- {recommendation}"
        )


def _display_strengths(strengths: list):
    """
    Display resume strengths.
    Parameters: strengths (list): Resume strengths.
    Returns: None
    """
    _display_tag_list(
        title=STRENGTHS,
        icon="💪",
        items=strengths,
        empty_message=NO_STRENGTHS_MESSAGE,
    )


def _get_score_status(ats_score: int):
    """
    Determine the ATS score category.
    Parameters: ats_score (int): ATS score generated by Gemini.
    Returns:
        tuple: Status, icon and description.
    """
    if ats_score >= 80:
        return (
            EXCELLENT_MATCH,
            EXCELLENT_MATCH_ICON,
            EXCELLENT_MATCH_DESCRIPTION
        )
    if ats_score >= 60:
        return (
            GOOD_MATCH,
            GOOD_MATCH_ICON,
            GOOD_MATCH_DESCRIPTION
        )
    return (
        NEEDS_IMPROVEMENT,
        NEEDS_IMPROVEMENT_ICON,
        NEEDS_IMPROVEMENT_DESCRIPTION
    )


def display_analysis_dashboard(analysis: dict):
    """
    Display the resume analysis dashboard.
    Parameters: analysis (dict): Resume analysis returned by Gemini.
    Returns: None
    """
    _display_summary(
        summary=analysis[SUMMARY],
        recommendation_level=analysis[RECOMMENDATION_LEVEL]
    )
    st.divider()
    _display_score_section(
        ats_score=analysis[ATS_SCORE]
    )
    st.divider()
    left_column, right_column = st.columns(2)
    with left_column:
        _display_tag_list(
            title=MATCHING_SKILLS,
            icon="✅",
            items=analysis[MATCHING_SKILLS],
            empty_message=NO_MATCHING_SKILLS_MESSAGE
        )
    with right_column:
        _display_tag_list(
            title=MISSING_SKILLS,
            icon="❌",
            items=analysis[MISSING_SKILLS],
            empty_message=NO_MISSING_SKILLS_MESSAGE
        )
    st.divider()
    _display_strengths(
        strengths=analysis[STRENGTHS]
    )
    st.divider()
    _display_recommendations(
        recommendations=analysis[RECOMMENDATIONS]
    )
    st.divider()
    markdown_report = generate_markdown_report(
        analysis_data=analysis
    )
    st.download_button(
        label=MARKDOWN_REPORT_BUTTON_LABEL,
        data=markdown_report,
        file_name=MARKDOWN_REPORT_FILE_NAME,
        mime=MARKDOWN_REPORT_MIME_TYPE
    )
