import streamlit as st
from src.constants import (
    ATS_SCORE,
    MATCHING_SKILLS,
    MISSING_SKILLS,
    RECOMMENDATIONS,
    STRENGTHS,
)


def _display_bullet_list(title: str, icon: str, items: list):
    """
    Display a titled list of skills.
    Parameters:
        title (str): Section heading.
        icon (str): Emoji displayed before the heading.
        skills (list): List of skills to display.
    Returns: None
    """
    if title:
        st.subheader(
            f"{icon} {title}"
        )
    if not items:
        st.write("- None")
        return
    for item in items:
        st.markdown(
            f"- {item}"
        )


def _display_score_section(ats_score: int):
    """
    Display the ATS score section.
    Parameters: ats_score (int): ATS score generated by Gemini.
    Returns: None
    """
    score_status, score_icon = _get_score_status(
        ats_score=ats_score
    )
    st.subheader("🎯 ATS Match Score")
    st.metric(
        label=f"{score_icon} {score_status}",
        value=f"{ats_score}%"
    )
    st.progress(
        ats_score / 100
    )


def _display_recommendations(recommendations: list):
    """
    Display resume recommendations.
    Parameters: recommendations (list): Improvement recommendations.
    Returns: None
    """
    with st.expander(
        "💡 Recommendations",
        expanded=True):
        _display_bullet_list(
            title="",
            icon="",
            items=recommendations
        )


def _display_strengths(strengths: list):
    """
    Display resume strengths.
    Parameters: strengths (list): Resume strengths.
    Returns: None
    """
    _display_bullet_list(
        title="Strengths",
        icon="💪",
        items=strengths
    )


def _get_score_status(ats_score: int):
    """
    Determine the ATS score category.
    Parameters: ats_score (int): ATS score generated by Gemini.
    Returns: tuple: Status label and color indicator.
    """
    if ats_score >= 80:
        return "Excellent Match", "🟢"
    if ats_score >= 60:
        return "Good Match", "🟡"
    return "Needs Improvement", "🔴"



def display_analysis_dashboard(analysis: dict):
    """
    Display the resume analysis dashboard.
    Parameters: analysis (dict): Resume analysis returned by Gemini.
    Returns: None
    """
    _display_score_section(
        ats_score=analysis[ATS_SCORE]
    )
    st.divider()
    left_column, right_column = st.columns(2)
    with left_column:
        _display_bullet_list(
            title="Matching Skills",
            icon="✅",
            items=analysis[MATCHING_SKILLS]
        )
    with right_column:
        _display_bullet_list(
            title="Missing Skills",
            icon="❌",
            items=analysis[MISSING_SKILLS]
        )
    st.divider()
    _display_strengths(
        strengths=analysis[STRENGTHS]
    )
    st.divider()
    _display_recommendations(
        recommendations=analysis[RECOMMENDATIONS]
    )
    